# Custom Language File for Launcher Customizer

[ejs.app]
title = "Strobic Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/CelLauncher/CelestialLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/CelLauncher/CelestialLauncher"
supportLink = "https://github.com/CelLauncher/CelestialLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO STROBIC ORIGINS"
welcomeDescription = "Remind me to type something here for your server, or rather... Send me something."
welcomeDescCTA = "Now click below to authenticate ya wanka"
