# Custom Language File for Launcher Customizer

[ejs.app]
title = "Strobic Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/CelestialStudiosLLC/StrobicLauncher"
mediaTwitterURL = "https://twitter.com/CelestialStud"
mediaInstagramURL = "http://instagram.com/"
mediaYouTubeURL = "https://www.youtube.com/@CelestialStud"
mediaDiscordURL = "https://discord.gg/strobic"

[ejs.settings]
sourceGithubLink = "https://github.com/CelestialStudiosLLC/StrobicLauncher"
supportLink = "https://github.com/CelestialStudiosLLC/StrobicLauncher/issues"

[ejs.welcome]
welcomeHeader = "Welcome to StrobicTV!"
welcomeDescription = "Home of the best Modded Minecraft Network on the platform."
welcomeDescCTA = "Click below to login!"
